name: commit_lint
description: Static analysis for commit messages
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  conventional_commit: ^0.4.0
  meta: ^1.3.0
  yaml: ^3.1.0
  collection: ^1.15.0
  args: ^2.0.0
  process_run: ^0.12.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

executables:
  commit-lint: